theme: jekyll-theme-hacker
repository: Logerfo/logerfo.github.io
github: [metadata]
google_analytics: UA-148828272-1
title: Bruno Logerfo
description: bruno@logerfo.com.br
github:
  repository_url: https://github.com/Logerfo/logerfo.github.io
profile:
  picture: https://avatars1.githubusercontent.com/u/19306384
  picture_url: https://github.com/Logerfo
  url: https://logerfo.tk
  description_url: mailto:bruno@logerfo.com.br
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
    values:
      header: true
